### ISSUE TITLE
Weighted networks, seems that weights are not taken into consideration.

### ISSUE THREAD

**Issue by jacopomoi** [ABenatti/network_symmetry#5]
It seems to me that weights are not take in account. As an example:

A network with 16 Nodes, uniform weights on edges equal to 1,h=5.
Node color is accessibility
[try_acc.zip](https://github.com/ABenatti/network_symmetry/files/12048243/try_acc.zip)

![image](https://github.com/ABenatti/network_symmetry/assets/91873409/aa15f111-ba36-4f2a-9efe-4eb23e5a1237)

In this case the edge weights are sampled from a uniform distribution, with min=1, max=1000
![image](https://github.com/ABenatti/network_symmetry/assets/91873409/e1ecc4f6-499a-465f-bbbc-2d31e3503eb3)

I attached the jupyter notebook.

it's not clear to me if I misunderstood something about accessibility, but if I'm not mistaken Self Avoiding RWs should generate a different transition matrix depending on the weight of the arcs.

Thanks!

**Comment by filipinascimento** [comment]
Sorry for the late response. We were in conferences over the past weeks. We will investigate the issue in the next few days. It was supposed to work with the weights, so something may be wrong on our side. I will check with the other developers too.

thanks!

**Comment by jacopomoi** [comment]
Thank you very much! :)

**Comment by hfarruda** [comment]
Sorry for the late response. We fixed the issue, and now the measures are working for weighted networks. If you want to use it, the new version is available on PIP.
